export const RECEIVE_PROJECT = 'RECEIVE_PROJECT';

export const SET_ACTIVE_ARTBOARD = 'SET_ACTIVE_ARTBOARD';
export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';
export const SET_OPEN_PAGE = 'SET_OPEN_PAGE';

export const CLICK_ARTBOARD_LAYER = 'CLICK_ARTBOARD_LAYER';
export const ENTER_ARTBOARD_LAYER = 'ENTER_ARTBOARD_LAYER';
export const LEAVE_ARTBOARD_LAYER = 'LEAVE_ARTBOARD_LAYER';

export const SET_BACKGROUND_COLOR = 'SET_BACKGROUND_COLOR';
export const SET_MARKER_COLOR = 'SET_MARKER_COLOR';

export const CHANGE_VIEW_MODE = 'CHANGE_VIEW_MODE';
export const CHANGE_FILTER = 'CHANGE_FILTER';

export const ZOOM_ARTBOARD = 'ZOOM_ARTBOARD';
export const SCALE_ARTBOARD = 'SCALE_ARTBOARD';
export const TAKE_ARTBOARD = 'TAKE_ARTBOARD';
export const DROP_ARTBOARD = 'DROP_ARTBOARD';
export const DRAG_ARTBOARD = 'DRAG_ARTBOARD';

export const CHANGE_SIZE_DROPDOWN = 'CHANGE_SIZE_DROPDOWN';
export const CHANGE_FORMAT_DROPDOWN = 'CHANGE_FORMAT_DROPDOWN';
export const CLICK_DROPDOWN = 'CLICK_DROPDOWN';
export const TOGGLE_SETTING_PANEL = 'TOGGLE_SETTING_PANEL';
