module.exports = {

    ActionTypes: {
        RECEIVE_PROJECT: 'RECEIVE_PROJECT',
        CLICK_NAV_ARTBOARD: 'CLICK_NAV_ARTBOARD',
        CLICK_NAV_FOLDER: 'CLICK_NAV_FOLDER',
        CHANGE_VIEW_MODE: 'CHANGE_VIEW_MODE',
        CLICK_ARTBOARD_LAYER: 'CLICK_ARTBOARD_LAYER',
        ENTER_ARTBOARD_LAYER: 'ENTER_ARTBOARD_LAYER',
        LEAVE_ARTBOARD_LAYER: 'LEAVE_ARTBOARD_LAYER',
        SET_MARKER_COLOR: 'SET_MARKER_COLOR',
        SET_BACKGROUND_COLOR: 'SET_BACKGROUND_COLOR'
    }

};
